#!/bin/sh

case "$1" in
    "")
        echo "Usage: $0 [production|local]"
        ;;
    "production")
        echo "Starting the app..."
        grunt build:dist
        NODE_ENV=production npm start
        ;;
    "local")
        echo "Starting the app..."
        
        NODE_ENV=development PORT=3002 node app.js
        ;;
esac
